# Generated by Django 5.2.6 on 2025-12-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "departamentos",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "distritos",
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "tipos_documento",
            },
        ),
        migrations.CreateModel(
            name="IrrigationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "tipos_riego",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.CharField(max_length=100, unique=True)),
                ("price", models.FloatField()),
            ],
            options={
                "db_table": "precios",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="Activo", max_length=50)),
            ],
            options={
                "db_table": "productos",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("capacity", models.FloatField(null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="Activo", max_length=50)),
            ],
            options={
                "db_table": "almacenes",
            },
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("document", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("zone", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="Activo", max_length=50)),
                (
                    "deliveries_count",
                    models.IntegerField(db_column="deliveries", default=0),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.district",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.documenttype",
                    ),
                ),
            ],
            options={
                "db_table": "agricultores",
            },
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("area", models.FloatField(null=True)),
                ("altitude", models.FloatField(null=True)),
                ("status", models.CharField(default="Activo", max_length=50)),
                (
                    "distrito",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.district",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        db_column="farmerId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.farmer",
                    ),
                ),
                (
                    "tipo_riego",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.irrigationtype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="productId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "terrenos",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "product_state",
                    models.CharField(
                        choices=[("baba", "baba"), ("seco", "seco")],
                        default="seco",
                        max_length=50,
                    ),
                ),
                ("weight_fresh", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField()),
                ("conversion_factor", models.FloatField(default=0.38)),
                ("price_per_kg", models.FloatField(blank=True, null=True)),
                ("total_payment", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(default="Pendiente", max_length=50)),
                ("date", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "location_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        db_column="farmerId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.farmer",
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        db_column="landId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.land",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="productId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        db_column="warehouseId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "entregas",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(null=True)),
                ("date", models.CharField(max_length=50, null=True)),
                ("method", models.CharField(max_length=50, null=True)),
                ("reference", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(default="Completado", max_length=50)),
                (
                    "delivery",
                    models.ForeignKey(
                        db_column="deliveryId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.delivery",
                    ),
                ),
            ],
            options={
                "db_table": "pagos",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.department"
                    ),
                ),
            ],
            options={
                "db_table": "provincias",
                "unique_together": {("nombre", "departamento")},
            },
        ),
        migrations.AddField(
            model_name="district",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.province"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("nombre", "provincia")},
        ),
    ]
